[package]
name = "chronver"
version = "0.2.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
rust-version = "1.56"
license = "MIT"
readme = "README.md"
description = "Chronologic version parsing."
homepage = "https://github.com/dnaka91/chronver"
repository = "https://github.com/dnaka91/chronver"
keywords = ["version", "chronologic"]
categories = ["development-tools", "parsing"]
exclude = [".github", ".gitignore", "deny.toml", "release.toml"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
serde = { version = "1.0.130", optional = true, features = ["derive"] }
thiserror = "1.0.30"
time = { version = "0.3.3", features = ["formatting", "macros", "parsing"] }

[dev-dependencies]
criterion = "0.3.5"
semver = "1.0.4"
serde_json = "1.0.68"
version-sync = "0.9.3"

[[bench]]
name = "parse"
harness = false
