[package]
name = "chronver"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Chronologic version parsing."
homepage = "https://github.com/dnaka91/chronver"
repository = "https://github.com/dnaka91/chronver"
keywords = ["version", "chronologic"]
categories = ["development-tools", "parsing"]
exclude = [".gitignore", "deny.toml"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
chrono = "0.4.19"
serde = { version = "1.0.117", optional = true, features = ["derive"] }
thiserror = "1.0.22"

[dev-dependencies]
criterion = "0.3.3"
semver = "0.11.0"
serde_json = "1.0.59"
version-sync = "0.9.1"

[[bench]]
name = "parse"
harness = false
