sign-commit = true
sign-tag = true
# Generate the changelog
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
pre-release-commit-message = "chore: release v{{version}}"
tag-message = "chore: release v{{version}}"

# Update README.md version
[[pre-release-replacements]]
file = "README.md"
search = 'chronver = "[a-z0-9\.-]+"'
replace = 'chronver = "{{version}}"'
