sign-commit = true
sign-tag = true
dev-version = false

# Update README.md version
[[pre-release-replacements]]
file = "README.md"
search = 'chronver = "[a-z0-9\.-]+"'
replace = 'chronver = "{{version}}"'

# Update lib.rs docs root URL
[[pre-release-replacements]]
file = "src/lib.rs"
search = '#!\[doc\(html_root_url = "https://docs\.rs/chronver/[a-z0-9\.-]+"\)\]'
replace = '#![doc(html_root_url = "https://docs.rs/chronver/{{version}}")]'

# Add new version entry to CHANGELOG.md
[[pre-release-replacements]]
file = "CHANGELOG.md"
search = '##\s*\[Unreleased\]\s*-\s*ReleaseDate'
replace = '''
## [Unreleased] - ReleaseDate

## [{{version}}] - {{date}}'''

# Add new comparison link to CHANGELOG.md
[[pre-release-replacements]]
file = "CHANGELOG.md"
search = '\[Unreleased\]:.+HEAD'
replace = '''
[Unreleased]: https://github.com/dnaka91/chronver/compare/v{{version}}...HEAD
[{{version}}]: https://github.com/dnaka91/chronver/compare/v{{prev_version}}...v{{version}}'''
